def PrintMainConsoleFunctions():
    print(" = MAIN = ")
    print("Select one option + ENTER:")
    print("1 - ConnectionSettings")
    print("2 - DOC functions (+ auto connect)")
    print("V - Version information")
    print("H - Change RESTful destination")
    print("0 - <EXIT>")
    print("---------------------------------------")

def PrintConnectionSettingsFunctions():
    print(" = ConnectionSettings =")
    print("Select one option + ENTER:")
    print("1 - GET possible settings")
    print("2 - GET current settings")
    print("3 - POST new settings")
    print("0 - <BACK>")
    print("---------------------------------------")

def PrintDocFunctions():
    print(" = DOC functions =")
    print("Select one option + ENTER:")
    print("1 - GET IsConnected")
    print("2 - GET ReaderInfo")
    print("3 - GET Identify")
    print("4 - GET ReadBytes")
    print("5 - POST WriteBytes")
    print("6 - GET SensorData")
    print("7 - SSE IdentifyCycle")
    print("8 - SSE GetSensorDataCycle")
    print("A - GET Timeout")
    print("B - POST Timeout")
    print("0 - <BACK> (+ auto disconnect)")
    print("---------------------------------------")